apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argowf-chaos-pod-delete-
  namespace: litmus
  labels:
    subject: "{{workflow.parameters.appNamespace}}_kube-proxy"
spec:
  entrypoint: argowf-chaos
  serviceAccountName: argo-chaos
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  arguments:
    parameters:
      - name: adminModeNamespace
        value: "litmus"
      - name: appNamespace
        value: "kube-system"
  templates:
    - name: argowf-chaos
      steps:
        - - name: install-experiment
            template: install-experiment
        - - name: run-chaos
            template: run-chaos
        - - name: revert-chaos
            template: revert-chaos

    - name: install-chaos-experiments
        container:
          image: litmuschaos/k8s:latest
          command: [ sh, -c ]
          args:
            - "kubectl apply -f https://hub.litmuschaos.io/api/chaos/master?file=charts/generic/experiments.yaml -n
                {{workflow.parameters.adminModeNamespace}} ; sleep 30"

    - name: run-chaos
      inputs:
        artifacts:
          - name: run-chaos
            path: /tmp/chaosengine.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  name: kube-proxy-pod-delete-chaos
                  namespace: {{workflow.parameters.adminModeNamespace}}
                  labels:
                    context: "{{workflow.parameters.appNamespace}}_kube-proxy"
                spec:
                  appinfo:
                    appns: kube-system
                    applabel: "k8s-app=kube-proxy"
                    appkind: daemonset
                  jobCleanUpPolicy: retain
                  engineState: 'active'
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-delete
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
      container:
        image: litmuschaos/litmus-checker:latest
        args: ["-file=/tmp/chaosengine.yaml","-saveName=/tmp/engine-name"]

    - name: revert-chaos
      container:
        image: litmuschaos/k8s:latest
        command: [sh, -c]
        args:
          [
            "kubectl delete chaosengine kube-proxy-pod-delete-chaos -n {{workflow.parameters.adminModeNamespace}}",
          ]
